version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always


  frontend: 
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://ctf.avail.global
    volumes:
      - ./frontend:/app
    depends_on:
      - mongodb
    restart: always

  backend:
    build: ./backend
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb-data:

    