version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 3001:3000
    environment:
      - PUBLIC_NEXT_API_URL=https://ctf.avail.global
    volumes:
      - ./frontend:/app
    depends_on:
      - mongodb
    restart: always

  backend:
    build: ./backend
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - 6123:6123
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb-data:
